package com.cyrcetech.interface_adapter.controller;

import com.cyrcetech.app.CyrcetechApp;
import com.cyrcetech.app.DependencyContainer;
import com.cyrcetech.entity.Customer;
import com.cyrcetech.entity.DeviceType;
import com.cyrcetech.entity.Equipment;
import com.cyrcetech.entity.Ticket;
import com.cyrcetech.usecase.AIService;
import com.cyrcetech.infrastructure.api.service.CustomerApiService;
import com.cyrcetech.infrastructure.api.service.EquipmentApiService;
import com.cyrcetech.infrastructure.api.service.TicketApiService;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.*;

import java.io.IOException;

public class NewTicketController {

    @FXML
    private TextField nameField;
    @FXML
    private TextField taxIdField;
    @FXML
    private TextField addressField;
    @FXML
    private TextField phoneField;

    @FXML
    private ComboBox<DeviceType> deviceTypeCombo;
    @FXML
    private TextField brandField;
    @FXML
    private TextField modelField;
    @FXML
    private TextField serialField;
    @FXML
    private TextArea problemArea;
    @FXML
    private TextArea observationsArea;
    @FXML
    private TextArea aiDiagnosisArea;
    @FXML
    private TextField downPaymentField;
    @FXML
    private TextField estimatedCostField;

    private final AIService aiService = DependencyContainer.getAiService();
    private final TicketApiService ticketApiService = new TicketApiService();
    private final CustomerApiService customerApiService = new CustomerApiService();
    private final EquipmentApiService equipmentApiService = new EquipmentApiService();

    @FXML
    public void initialize() {
        deviceTypeCombo.setItems(FXCollections.observableArrayList(DeviceType.values()));

        // Custom cell factory to show icons with device names
        deviceTypeCombo.setCellFactory(lv -> new ListCell<DeviceType>() {
            @Override
            protected void updateItem(DeviceType item, boolean empty) {
                super.updateItem(item, empty);
                if (empty || item == null) {
                    setText(null);
                } else {
                    setText(item.getFormattedName()); // Shows "💻 Notebook"
                    setStyle("-fx-text-fill: white;");
                }
            }
        });

        // Also show icon in the button cell (when selected)
        deviceTypeCombo.setButtonCell(new ListCell<DeviceType>() {
            @Override
            protected void updateItem(DeviceType item, boolean empty) {
                super.updateItem(item, empty);
                if (empty || item == null) {
                    setText(null);
                } else {
                    setText(item.getFormattedName());
                    setStyle("-fx-text-fill: white;");
                }
            }
        });
    }

    @FXML
    private void handleConsultAI(ActionEvent event) {
        String type = deviceTypeCombo.getValue() != null ? deviceTypeCombo.getValue().toString() : "Desconocido";
        String problem = problemArea.getText();

        if (problem == null || problem.isEmpty()) {
            Alert alert = new Alert(Alert.AlertType.WARNING);
            alert.setContentText("Por favor describa el problema primero.");
            alert.show();
            return;
        }

        String diagnosis = aiService.getDiagnosis(type, problem);
        aiDiagnosisArea.setText(diagnosis);
    }

    @FXML
    private void handleSave(ActionEvent event) throws IOException {
        Ticket ticket = new Ticket();

        try {
            double downPayment = 0;
            if (downPaymentField.getText() != null && !downPaymentField.getText().isEmpty()) {
                downPayment = Double.parseDouble(downPaymentField.getText());
            }
            double estimatedCost = 0;
            if (estimatedCostField.getText() != null && !estimatedCostField.getText().isEmpty()) {
                estimatedCost = Double.parseDouble(estimatedCostField.getText());
            }

            ticket.setDownPayment(downPayment);
            ticket.setAmountPaid(downPayment); // Initial payment is the down payment
            ticket.setEstimatedCost(estimatedCost);

        } catch (NumberFormatException e) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setContentText("Monto inválido en Seña o Costo. Use solo números.");
            alert.show();
            return;
        }

        // Create and save customer
        Customer customer = Customer.create(
                "", // id will be generated by service
                nameField.getText(),
                taxIdField.getText(),
                addressField.getText(),
                phoneField.getText());

        try {
            Customer savedCustomer = customerApiService.createCustomer(customer);

            // Create and save equipment linked to customer
            Equipment equipment = new Equipment(
                    "", // id generated by service/db
                    brandField.getText(),
                    modelField.getText(),
                    deviceTypeCombo.getValue(),
                    serialField.getText(),
                    "", // physical condition not yet in form
                    savedCustomer.id() // Link to saved customer
            );

            Equipment savedEquipment = equipmentApiService.createEquipment(equipment);

            ticket.setCustomer(savedCustomer);
            ticket.setEquipment(savedEquipment);
            ticket.setProblemDescription(problemArea.getText());
            ticket.setObservations(observationsArea.getText());
            ticket.setAiDiagnosis(aiDiagnosisArea.getText());

            ticketApiService.createTicket(ticket);

            Alert alert = new Alert(Alert.AlertType.INFORMATION);
            alert.setContentText("Ticket creado exitosamente!");
            alert.showAndWait();

            CyrcetechApp.setRoot("view/MainView");
        } catch (Exception e) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setContentText("Error creando ticket: " + e.getMessage());
            alert.show();
            e.printStackTrace();
        }
    }

    @FXML
    private void handleCancel(ActionEvent event) throws IOException {
        CyrcetechApp.setRoot("view/MainView");
    }
}
