package com.cyrcetech.interface_adapter.controller;

import com.cyrcetech.app.CyrcetechApp;
import com.cyrcetech.app.DependencyContainer;
import com.cyrcetech.entity.Customer;
import com.cyrcetech.entity.DeviceType;
import com.cyrcetech.entity.Equipment;
import com.cyrcetech.entity.Ticket;
import com.cyrcetech.usecase.AIService;
import com.cyrcetech.usecase.CustomerService;
import com.cyrcetech.usecase.EquipmentService;
import com.cyrcetech.usecase.TicketService;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.*;

import java.io.IOException;

public class NewTicketController {

    @FXML
    private TextField nameField;
    @FXML
    private TextField taxIdField;
    @FXML
    private TextField addressField;
    @FXML
    private TextField phoneField;

    @FXML
    private ComboBox<DeviceType> deviceTypeCombo;
    @FXML
    private TextField brandField;
    @FXML
    private TextField modelField;
    @FXML
    private TextField serialField;
    @FXML
    private TextArea problemArea;
    @FXML
    private TextArea observationsArea;
    @FXML
    private TextArea aiDiagnosisArea;

    private final AIService aiService = DependencyContainer.getAiService();
    private final TicketService ticketService = DependencyContainer.getTicketService();
    private final CustomerService customerService = DependencyContainer.getCustomerService();
    private final EquipmentService equipmentService = DependencyContainer.getEquipmentService();

    @FXML
    public void initialize() {
        deviceTypeCombo.setItems(FXCollections.observableArrayList(DeviceType.values()));
    }

    @FXML
    private void handleConsultAI(ActionEvent event) {
        String type = deviceTypeCombo.getValue() != null ? deviceTypeCombo.getValue().toString() : "Desconocido";
        String problem = problemArea.getText();

        if (problem == null || problem.isEmpty()) {
            Alert alert = new Alert(Alert.AlertType.WARNING);
            alert.setContentText("Por favor describa el problema primero.");
            alert.show();
            return;
        }

        String diagnosis = aiService.getDiagnosis(type, problem);
        aiDiagnosisArea.setText(diagnosis);
    }

    @FXML
    private void handleSave(ActionEvent event) throws IOException {
        Ticket ticket = new Ticket();

        // Create and save customer
        Customer customer = new Customer(
                "", // id will be generated by service
                nameField.getText(),
                taxIdField.getText(),
                addressField.getText(),
                phoneField.getText());

        Customer savedCustomer = customerService.createCustomer(customer);

        // Create and save equipment linked to customer
        Equipment equipment = new Equipment(
                "", // id generated by service/db
                brandField.getText(),
                modelField.getText(),
                deviceTypeCombo.getValue(),
                serialField.getText(),
                "", // physical condition not yet in form
                savedCustomer.id() // Link to saved customer
        );

        Equipment savedEquipment = equipmentService.createEquipment(equipment);

        ticket.setCustomer(savedCustomer);
        ticket.setEquipment(savedEquipment);
        ticket.setProblemDescription(problemArea.getText());
        ticket.setObservations(observationsArea.getText());
        ticket.setAiDiagnosis(aiDiagnosisArea.getText());

        ticketService.createTicket(ticket);

        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setContentText("Ticket creado exitosamente!");
        alert.showAndWait();

        CyrcetechApp.setRoot("view/MainView");
    }

    @FXML
    private void handleCancel(ActionEvent event) throws IOException {
        CyrcetechApp.setRoot("view/MainView");
    }
}
